# Generated by Django 2.2 on 2020-09-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceitem_icon_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0002_contactwithitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_content', models.TextField(blank=True, null=True)),
                ('Project_Complete', models.IntegerField(blank=True, default=1, null=True)),
                ('Happy_Clients', models.IntegerField(blank=True, default=1, null=True)),
                ('Business_Partners', models.IntegerField(blank=True, default=1, null=True)),
                ('B2b_Consultant', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_head_title', models.CharField(blank=True, max_length=50, null=True)),
                ('promo_head_sub_content', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='img/icon')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_content', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_banner', models.ImageField(blank=True, null=True, upload_to='promo/img')),
                ('plank_left', models.BooleanField(default=False)),
                ('plank_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_about', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='worker/img')),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
