# Generated by Django 2.2 on 2020-09-28 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_about_aboutpromo_aboutteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='left_banner_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='promo/img'),
            preserve_default=False,
        ),
    ]
