# Generated by Django 2.2 on 2020-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_about_left_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPromoLeftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='img/icon')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_content', models.CharField(blank=True, max_length=100, null=True)),
                ('plank_left', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPromoRightItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='img/icon')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_content', models.CharField(blank=True, max_length=100, null=True)),
                ('plank_right', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPromoTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_head_title', models.CharField(blank=True, max_length=50, null=True)),
                ('promo_head_sub_content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPromo',
        ),
    ]
