# Generated by Django 2.2 on 2020-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20200928_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPromoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/img')),
            ],
        ),
    ]
