# Generated by Django 2.2 on 2020-09-27 07:23

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
