# Generated by Django 2.2 on 2020-09-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_category_strategicwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='icon_v2',
            field=models.ImageField(blank=True, null=True, upload_to='icon/img'),
        ),
    ]
